defaults:
  - model/maxvit_yolox/default
  - _self_

checkpoint: "/data/hamaraa/rvt-b_eTraM.ckpt"
dataset:
  name: "gen4"
  downsample_by_factor_2: True
use_test_set: False
hardware:
  num_workers:
    eval: 4
  gpus: 0 # GPU idx (multi-gpu not supported for validation)
batch_size:
  eval: 8
training:
  precision: 16
