defaults:
  - base
  - maxvit_yolox/default

name: rnndet
dataset: gen4

checkpoint: "/Users/andrewhamara/models/rvt-b_eTraM.ckpt"
use_test_set: False

hardware:
  num_workers:
    eval: 4
  gpus: 0 # GPU idx (multi-gpu not supported for validation)
batch_size:
  eval: 8
training:
  precision: 16

backbone:
  name: MaxViTRNN

fpn:
  name: PAFPN
head:
  name: YoloX
postprocess:
  confidence_threshold: 0.1
  nms_threshold: 0.45
